# pose covariance (x, y, z, roll, pitch, yaw)
pose_covariance: [  0.1,    0,    0,    0,    0,    0,
                      0,  0.1,    0,    0,    0,    0,
                      0,    0,  0.1,    0,    0,    0,
                      0,    0,    0,    0,    0,    0,
                      0,    0,    0,    0,    0,    0,
                      0,    0,    0,    0,    0,    0]

# twist covariance  (x, y, z, roll, pitch, yaw)
twist_covariance: [    0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0,
                       0,    0,    0,    0,    0,    0]
